console.log("Kimmi");
const score =45;
console.log(score);
const num= new Number(122);
console.log(num);
console.log (score.toFixed(2));
console.log (num.toString(2));
const num1=123.89;
console.log(num1.toPrecision(3));
const num2=100000;
console.log(num2.toLocaleString('en-IN'));
